openapi: 3.0.0
info:
  title: Product API
  description: API for managing products, including CRUD operations.
  version: 1.0.0
paths:
  /products:
    get:
      summary: Retrieve all products
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Number of products to return
        - in: query
          name: page
          schema:
            type: integer
          description: Page number for pagination
        - in: query
          name: query
          schema:
            type: string
          description: Search query to filter products
        - in: query
          name: sort
          schema:
            type: string
          description: Sort order (e.g., 'price', 'name')
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The unique identifier for the product
                    name:
                      type: string
                      description: The name of the product
                    price:
                      type: number
                      format: float
                      description: The price of the product
                    description:
                      type: string
                      description: A description of the product
                    stock:
                      type: integer
                      description: The number of items in stock

    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                  format: float
                description:
                  type: string
                stock:
                  type: integer
      responses:
        "201":
          description: The created product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
                    format: float
                  description:
                    type: string
                  stock:
                    type: integer

  /products/{pid}:
    get:
      summary: Retrieve a specific product by ID
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A specific product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
                    format: float
                  description:
                    type: string
                  stock:
                    type: integer
        "404":
          description: Product not found

    put:
      summary: Update a specific product by ID
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                  format: float
                description:
                  type: string
                stock:
                  type: integer
      responses:
        "200":
          description: The updated product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
                    format: float
                  description:
                    type: string
                  stock:
                    type: integer
        "404":
          description: Product not found

    delete:
      summary: Delete a specific product by ID
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Confirmation of product deletion
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        "404":
          description: Product not found
